version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-{{ checksum "package-lock.json" }}
            - v1-npm-
      - run: npm install
      - save_cache:
          key: v1-npm-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - restore_cache:
          keys:
            - v1-bundle-{{ checksum "Gemfile.lock" }}
            - v1-bundle-
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: npm run build
      - restore_cache:
          key: v1-phantomjs-2.1.1    
            
      - run:
          name: Install phantomjs
          command: |
            if ! [ $(which phantomjs) ]; then                
              sudo curl --output /usr/local/bin/phantomjs https://s3.amazonaws.com/circle-downloads/phantomjs-2.1.1
            fi
                  
            sudo chmod ugo+x /usr/local/bin/phantomjs

      - save_cache:
          key: v1-phantomjs-2.1.1
          paths:            
            - /usr/local/bin/phantomjs
      - run: bundle exec htmlproofer _site
      - run: npx a11y '_site/**/*.html'


workflows:
  version: 2
  commit:
    jobs:
      - build
