backend:
  name: github
  repo: 18F/federalist-uswds-jekyll
  base_url: https://federalistapp-staging.18f.gov
  auth_endpoint: auth/github

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - label: "Posts"
    name: "Posts"
    folder: "_posts/"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
